mgw/urls.py
## only for testing
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("mgw_api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

mgw_api/urls.py
# mgw_api/urls.py

from django.urls import path

from . import views

app_name = "mgw_api"
urlpatterns = [
    path("", views.upload_fasta, name="upload_fasta"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("search/", views.upload_fasta, name="upload_fasta"),
    path("signatures/", views.list_signature, name="list_signature"),
    path(
        "process_signature/<int:pk>/", views.process_signature, name="process_signature"
    ),
    path("delete_signature/<int:pk>/", views.delete_signature, name="delete_signature"),
    path("settings/", views.sourmash_settings, name="settings"),
    path("watches/", views.list_watches, name="list_watches"),
    path("results/", views.list_result, name="list_result"),
    path("result/<int:pk>/", views.result_table, name="result_table"),
    path(
        "result/<int:pk>/update_filters/", views.update_filters, name="update_filters"
    ),
    path("result/<int:pk>/update_sort/", views.update_sort, name="update_sort"),
    path("toggle_watch/<int:pk>/", views.toggle_watch, name="toggle_watch"),
    path("delete_result/<int:pk>/", views.delete_result, name="delete_result"),
    path(
        "check_status/<int:fasta_id>/",
        views.check_processing_status,
        name="check_status",
    ),
    path(
        "download/full/<int:pk>/", views.download_full_table, name="download_full_table"
    ),
    # path(
    #    "download/filtered/<int:pk>/",
    #    views.download_filtered_table,
    #    name="download_filtered_table",
    # ),
]

mgw_api/models.py
import gzip
import io
import re
from datetime import datetime
from functools import partial
from pathlib import Path

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.db import models

from mgw.settings import LOGGER


def validate_fasta_content(fieldfile):
    # check if first two lines are in fasta format
    try:
        if Path(fieldfile.path).suffix == ".gz":
            # Input file is gzipped. Might be in memory so we need to read
            # the actual contents and decompress them
            fasta = gzip.decompress(fieldfile.read()).decode("utf-8")
            fasta_io = io.StringIO(fasta)

            header = fasta_io.readline().strip()
            seq = fasta_io.readline().strip()
        else:
            header = fieldfile.readline().decode("utf-8").strip()
            seq = fieldfile.readline().decode("utf-8").strip()

        # Do actual validation. This is not exhaustive, it's only checking the
        # first couple of lines as a sanity check.
        if not re.match(r"^>", header):
            LOGGER.error(f"header: {header}")
            LOGGER.error(f"seq: {seq}")
            raise ValidationError(
                "File does not start with '>' character, invalid FASTA format."
            )
        elif not re.match(r"^[ACGTRYSWKMBDHVN.-]+$", seq, flags=re.IGNORECASE):
            LOGGER.error(f"header: {header}")
            LOGGER.error(f"seq: {seq}")
            raise ValidationError(
                "Sequence contains non-IUPAC characters, invalid FASTA format."
            )
    except Exception as e:
        raise ValidationError(f"Error reading file: {str(e)}")


def user_directory_path(instance, filename):
    date = datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    return f"user_{instance.user.id}/{filename}-{date}"


class Fasta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True, null=True)
    file = models.FileField(
        upload_to=user_directory_path,
        validators=[
            FileExtensionValidator(["fa", "fasta", "fsa", "fna", "gz"]),
            validate_fasta_content,
        ],
    )
    upload_date = models.DateTimeField(auto_now_add=True)
    size = models.IntegerField()
    processed = models.BooleanField(default=False)
    status = models.CharField(max_length=255, default="Pending")
    result_pk = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name or self.file.name

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class Signature(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    fasta = models.ForeignKey(Fasta, null=True, on_delete=models.SET_NULL)
    file = models.FileField(upload_to=user_directory_path)
    date = models.DateTimeField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    size = models.IntegerField(default=0)
    submitted = models.BooleanField(default=False)
    settings_used = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class Settings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    kmer = models.JSONField(default=partial(list, [21]), help_text="List of k-mers")
    database = models.JSONField(
        default=partial(list, ["SRA"]), help_text="List of databases"
    )
    containment = models.FloatField(
        default=0.10, help_text="Containment value (between 0 and 1)"
    )

    def clean(self):
        if not self.kmer:
            raise ValidationError("At least one kmer must be selected.")
        if not self.database:
            raise ValidationError("At least one database must be selected.")
        if not (0 <= self.containment <= 1):
            raise ValidationError("Containment value must be between 0 and 1.")

    def to_dict(self):
        return {
            "kmer": self.kmer,
            "database": self.database,
            "containment": self.containment,
        }


class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    signature = models.ForeignKey(Signature, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path, blank=True)
    num_results = models.PositiveIntegerField(default=0)
    kmer = models.JSONField(default=list)
    database = models.JSONField(default=list)
    containment = models.FloatField(default=0.10)
    date = models.DateField(auto_now_add=True)
    time = models.DateTimeField(auto_now_add=True)
    is_watched = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class DateField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        value = super().pre_save(model_instance, add)
        if value:
            value = value.date()
            return datetime.combine(value, datetime.min.time())
        return value


class FilterSetting(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    filters = models.JSONField(default=dict)  # {column_index: filter_value}
    range_filters = models.JSONField(
        default=dict
    )  # {column_index: [min_value, max_value]}
    sort_column = models.IntegerField(null=True, blank=True)
    sort_reverse = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.result.name} Filters"

mgw_api/forms.py
# mgw_api/forms.py

from django import forms

from mgw_api.models import Fasta
from mgw_api.models import FilterSetting
from mgw_api.models import Result
from mgw_api.models import Settings


class FastaForm(forms.ModelForm):
    class Meta:
        model = Fasta
        fields = ("name", "file")
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "placeholder": "Drop or rename a file here ...",
                    "style": "width: calc(100% - 0px); box-sizing: border-box; height: 40px; font-size: 16px; padding-left: 10px;",
                }
            ),
            # This list of suffixes sets a filter on the extensions shown in
            # the file picker, but the user can override this by selecting to
            # view "All files" and the file will still be accepted/uploadable
            "file": forms.FileInput(
                attrs={
                    "accept": ".fa,.fasta,.fsa,.FASTA,.fna,.fa.gz,.fasta.gz,.fsa.gz,.FASTA.gz,.fna.gz"
                }
            ),
        }


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SettingsForm(forms.ModelForm):
    kmer = forms.MultipleChoiceField(
        choices=[(21, "21 k-mer")],
        # We currently only have indexes for 21-mers. Hide the other k-mer
        # lengths for now.
        # choices=[(21, "21 k-mer"), (31, "31 k-mer"), (51, "51 k-mer")],
        widget=forms.CheckboxSelectMultiple,
        initial=[21],
    )
    database = forms.MultipleChoiceField(
        choices=[("SRA", "SRA database")],
        # We don't yet index any database other than SRA. Disable this for now.
        # choices=[("SRA", "SRA database"), ("RKI", "RKI database")],
        widget=forms.CheckboxSelectMultiple,
        initial=["SRA"],
    )
    containment = forms.FloatField(
        widget=forms.NumberInput(attrs={"min": 0, "max": 1, "step": 0.01}), initial=0.10
    )

    class Meta:
        model = Settings
        fields = ["kmer", "database", "containment"]


class WatchForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ["is_watched"]


class FilterSettingForm(forms.ModelForm):
    class Meta:
        model = FilterSetting
        fields = ["filters", "range_filters", "sort_column", "sort_reverse"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for column, value in self.instance.filters.items():
            self.fields[f"filter_{column}"] = forms.CharField(
                initial=value, required=False, label=f"{column} Filter"
            )
        for column, value in self.instance.filters.items():
            self.fields[f"filter_{column}"] = forms.CharField(
                initial=value, required=False, label=f"{column} Filter (supports regex)"
            )

        for column, range_values in self.instance.range_filters.items():
            min_val, max_val = range_values
            self.fields[f"range_min_{column}"] = forms.CharField(
                initial=min_val, required=False, label=f"{column} Min"
            )
            self.fields[f"range_max_{column}"] = forms.CharField(
                initial=max_val, required=False, label=f"{column} Max"
            )

mgw_api/templates/mgw_api/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Daniel Desirò" />
        <meta name="description"
              content="MetagenomeWatch provides a metagenome search engine able to search through petabyte scale databases in real time." />
        <title>MetagenomeWatch</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'mgw_api/pico.blue.min.css' %}">
        <link rel="stylesheet" href="{% static 'mgw_api/custom.css' %}">
        <link rel="icon" href="{% static 'mgw_api/satellite-dish-solid.svg' %}">
    </head>
    <body>
        <header>
            <div class="container">
                <nav>
                    <ul>
                        <li>
                            <a aria-label="MetagenomeWatch homepage"
                               href="{% url 'mgw_api:upload_fasta' %}">
                                <h1>
                                    <strong>
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             viewBox="0 0 512 512"
                                             class="logo-icon">
                                            <!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                            <path d="M192 32c0-17.7 14.3-32 32-32C383.1 0 512 128.9 512 288c0 17.7-14.3 32-32 32s-32-14.3-32-32C448 164.3 347.7 64 224 64c-17.7 0-32-14.3-32-32zM60.6 220.6L164.7 324.7l28.4-28.4c-.7-2.6-1.1-5.4-1.1-8.3c0-17.7 14.3-32 32-32s32 14.3 32 32s-14.3 32-32 32c-2.9 0-5.6-.4-8.3-1.1l-28.4 28.4L291.4 451.4c14.5 14.5 11.8 38.8-7.3 46.3C260.5 506.9 234.9 512 208 512C93.1 512 0 418.9 0 304c0-26.9 5.1-52.5 14.4-76.1c7.5-19 31.8-21.8 46.3-7.3zM224 96c106 0 192 86 192 192c0 17.7-14.3 32-32 32s-32-14.3-32-32c0-70.7-57.3-128-128-128c-17.7 0-32-14.3-32-32s14.3-32 32-32z" />
                                        </svg>
                                        MetagenomeWatch
                                    </strong>
                                </h1>
                            </a>
                        </li>
                    </ul>
                    <ul>
                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'mgw_api:upload_fasta' %}">Search</a>
                            </li>
                            <li>
                                <a href="{% url 'mgw_api:list_result' %}">Results</a>
                            </li>
                            <li>
                                <a href="{% url 'mgw_api:list_watches' %}">Watches</a>
                            </li>
                            <li>|</li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <li>{{ request.user.username }}</li>
                            <li>
                                <a href="{% url 'mgw_api:logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'mgw_api:login' %}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </header>
        <main class="container">
            {% block content %}
            {% endblock content %}
        </main>
        <footer>
            <div class="container">
                <!-- <p>&copy; MetagenomeWatch</p> -->
            </div>
        </footer>
    </body>
</html>

mgw_api/templates/mgw_api/base_result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Daniel Desirò" />
        <meta name="description"
              content="MetagenomeWatch provides a metagenome search engine able to search through petabyte scale databases in real time." />
        <title>MetagenomeWatch</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'mgw_api/pico.blue.min.css' %}">
        <link rel="stylesheet" href="{% static 'mgw_api/custom.css' %}">
        <link rel="icon" href="{% static 'mgw_api/satellite-dish-solid.svg' %}">
        <!-- required for datatables.net -->
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
                crossorigin="anonymous"></script>
        <link rel="stylesheet"
              href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />
        <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>
    </head>
    <body>
        <header>
            <div class="container-fluid">
                <nav>
                    <ul>
                        <li>
                            <a aria-label="MetagenomeWatch homepage"
                               href="{% url 'mgw_api:upload_fasta' %}">
                                <h1>
                                    <strong>
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             viewBox="0 0 512 512"
                                             class="logo-icon">
                                            <!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                            <path d="M192 32c0-17.7 14.3-32 32-32C383.1 0 512 128.9 512 288c0 17.7-14.3 32-32 32s-32-14.3-32-32C448 164.3 347.7 64 224 64c-17.7 0-32-14.3-32-32zM60.6 220.6L164.7 324.7l28.4-28.4c-.7-2.6-1.1-5.4-1.1-8.3c0-17.7 14.3-32 32-32s32 14.3 32 32s-14.3 32-32 32c-2.9 0-5.6-.4-8.3-1.1l-28.4 28.4L291.4 451.4c14.5 14.5 11.8 38.8-7.3 46.3C260.5 506.9 234.9 512 208 512C93.1 512 0 418.9 0 304c0-26.9 5.1-52.5 14.4-76.1c7.5-19 31.8-21.8 46.3-7.3zM224 96c106 0 192 86 192 192c0 17.7-14.3 32-32 32s-32-14.3-32-32c0-70.7-57.3-128-128-128c-17.7 0-32-14.3-32-32s14.3-32 32-32z" />
                                        </svg>
                                        MetagenomeWatch
                                    </strong>
                                </h1>
                            </a>
                        </li>
                    </ul>
                    <ul>
                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'mgw_api:upload_fasta' %}">Search</a>
                            </li>
                            <li>
                                <a href="{% url 'mgw_api:list_result' %}">Results</a>
                            </li>
                            <li>
                                <a href="{% url 'mgw_api:list_watches' %}">Watches</a>
                            </li>
                            <li>|</li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <li>{{ request.user.username }}</li>
                            <li>
                                <a href="{% url 'mgw_api:logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'mgw_api:login' %}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </header>
        <main class="container-fluid">
            {% block content %}
            {% endblock content %}
        </main>
        <footer>
            <div class="container-fluid">
                <!-- <p>&copy; MetagenomeWatch</p> -->
            </div>
        </footer>
    </body>
</html>

mgw_api/templates/mgw_api/list_result.html
{% extends "mgw_api/base.html" %}
{% block content %}
    <div class="signature-list" id="upload-section">
        <h2>Search Results</h2>
        <p>
            This page shows all previous searches you have done, grouped by the search/sequence name. You can set any previous search to be a Watch by ticking the "Is watched?" checkbox.
        </p>
        {% for signature in signatures %}
            <div class="signature-header">
                <div class="signature-name">
                    <h3>Sequence name: {{ signature.name }}</h3>
                </div>
                <div class="signature-actions">
                    {% if not signature.result_set.exists %}
                        <a href="{% url 'mgw_api:delete_signature' signature.pk %}?next={% url 'mgw_api:list_result' %}"
                           class="delete-link">delete</a>
                    {% endif %}
                    {% if False %}
                        <form class="search-form"
                              method="post"
                              action="{% url 'mgw_api:list_result' %}">
                            {% csrf_token %}
                            <input type="hidden" name="signature_id" value="{{ signature.pk }}">
                            <button type="submit">Update search</button>
                        </form>
                    {% endif %}
                </div>
            </div>
            {% if signature.result_set.exists %}
                Previous searches:
                <table class="result-list">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>K-mers</th>
                            <th>Databases</th>
                            <th>Containment</th>
                            <th># results</th>
                            <th>Is watched?</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for result in signature.sorted_results.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'mgw_api:result_table' result.pk %}">{{ result.date }} {{ result.time|date:"H:i:s" }}</a>
                                </td>
                                <td>{{ result.kmer }}</td>
                                <td>{{ result.database }}</td>
                                <td>{{ result.containment }}</td>
                                <td>{{ result.num_results }}</td>
                                <td>
                                    <form id="watch-form-{{ result.pk }}"
                                          method="post"
                                          action="{% url 'mgw_api:toggle_watch' result.pk %}">
                                        {% csrf_token %}
                                        <input type="checkbox"
                                               name="is_watched"
                                               {% if result.is_watched %}checked{% endif %}
                                               onchange="submitWatchForm({{ result.pk }})">
                                    </form>
                                </td>
                                <td>
                                    <a href="{% url 'mgw_api:delete_result' result.pk %}?next={% url 'mgw_api:list_result' %}">delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        {% empty %}
            <div class="no-signatures">
                <mark>No previous search results files found. Go to the <a href="{% url 'mgw_api:upload_fasta' %}">search page</a> and upload a seqeunce to do a new search.</mark>
            </div>
        {% endfor %}
    </div>
    <div class="waiting-message" id="waiting-message" style="display: none;">
        <ul class="messages">
            <li class="info">
                Searching for matches, please wait. Do not close or reload the page. This process might take a few minutes.
            </li>
        </ul>
    </div>
    <script>
    function handleError(message) {
        const submissionMessageDiv = document.querySelector('.submission-message');
        submissionMessageDiv.style.display = 'block';
        submissionMessageDiv.innerHTML = `<ul class="messages"><li class="error">An error occurred: ${message}</li></ul>`;
    }
    
    function submitWatchForm(resultId) {
        const form = document.getElementById(`watch-form-${resultId}`);
        const formData = new FormData(form);
    
        fetch(form.action, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: formData,
        }).then(response => {
            if (!response.ok) {
                handleError('Failed to update the watch status.');
            }
        });
    }

    function pollStatus(fastaId) {
        const url = `{% url 'mgw_api:check_status' 0 %}`.replace('0', fastaId);

        function checkStatus() {
            fetch(url)
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'Complete') {
                        window.location.href = `{% url 'mgw_api:result_table' 0 %}`.replace('0', data.result_pk);
                    } else if (data.status.startsWith('Error')) {
                        handleError(data.status);
                        document.getElementById('upload-section').style.display = 'block';
                        document.getElementById('waiting-message').style.display = 'none';
                    } else {
                        setTimeout(checkStatus, 5000);
                    }
                }).catch(error => {
                    handleError('An unexpected error occurred while checking the status.');
                    document.getElementById('upload-section').style.display = 'block';
                    document.getElementById('waiting-message').style.display = 'none';
                });
        }

        checkStatus();
    }

    function handleFormSubmission(event, headers = {}) {
        event.preventDefault();
        const form = event.target;
        const formData = new FormData(form);
    
        const uploadSection = document.getElementById('upload-section');
        const waitingMessage = document.getElementById('waiting-message');
    
        uploadSection.style.display = 'none';
        waitingMessage.style.display = 'block';
    
        fetch(form.action, {
            method: 'POST',
            headers: headers,
            body: formData,
        }).then(response => {
            if (!response.ok) {
                handleError(`Network response was not ok. Status: ${response.status} - ${response.statusText}`);
            }
            return response.json();
        }).then(data => {
            if (data.success) {
                pollStatus(data.fasta_id);
            } else {
                handleError(data.error || 'An unexpected error occurred.');
                uploadSection.style.display = 'block';
                waitingMessage.style.display = 'none';
            }
        }).catch(error => {
            handleError('An unexpected error occurred.');
            uploadSection.style.display = 'block';
            waitingMessage.style.display = 'none';
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('.search-form').forEach(form => {
            form.addEventListener('submit', function (event) {
                const headers = { 'X-CSRFToken': '{{ csrf_token }}' };
                handleFormSubmission(event, headers);
            });
        });
    });
    </script>
{% endblock content %}

mgw_api/templates/mgw_api/result_table.html
{% extends "mgw_api/base_result.html" %}
{% block content %}
    {% load custom_filters static %}
    <div class="result-navigation">
        <h2>Name: {{ result.name }}</h2>
        <p>Containment threshold: {{ result.containment }}</p>
        <form id="watch-form"
              method="post"
              action="{% url 'mgw_api:toggle_watch' result.pk %}">
            {% csrf_token %}
            <label>
                <input type="checkbox"
                       name="is_watched"
                       {% if result.is_watched %}checked{% endif %}
                       onchange="submitWatchForm()">
                Watched?
            </label>
        </form>
    </div>
    {% if not result.file %}
        <div>
            <mark>This search found zero results. Try redoing the search with a lower containment threshold.</mark>
        </div>
    {% else %}
        <div class="result-table">
            <div class="table-wrapper">
                <table id="results" class="display">
                    <thead id="table-head">
                        <tr>
                            {% for header in headers %}<th>{{ header }}</th>{% endfor %}
                        </tr>
                    </thead>
                    <tbody id="table-body">
                        {% for row in rows %}
                            <tr>
                                {% for cell, header in row|zip_lists:headers %}
                                    <td>
                                        {% if header == "sra link" or header == "biosample link" %}
                                            <a href="{{ cell }}" target="_blank">{{ cell|last_part_of_url }}</a>
                                        {% elif header == "containment" or header == "query containment ani" %}
                                            {{ cell|floatformat:4 }}
                                        {% elif header == "lat lon" %}
                                            {% if cell != "None" %}
                                                <a href="https://www.openstreetmap.org/#map=12/{{ cell|lat_lon_for_osm }}">view map</a>
                                            {% endif %}
                                        {% elif cell == "None" %}
                                        {% else %}
                                            {{ cell }}
                                        {% endif %}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div>
            Download: <a href="{% url 'mgw_api:download_full_table' result.pk %}">full unfiltered results (.tsv format)</a>
            <br>
            <a href="{% url 'mgw_api:delete_result' result.pk %}?next={% url 'mgw_api:result_table' result.pk %}">Delete this Result</a>
        </div>
    {% endif %}
    <script>
    // Remove the defaults
    DataTable.defaults.layout = {
        topStart: null,
        topEnd: null,
        bottomStart: null,
        bottomEnd: null
    };
    $(document).ready( function () {
        $('#results').DataTable( {
            order: [[7, 'desc']],
            layout: {
                topStart: 'info',
                topEnd: 'search',
                bottomEnd: ['pageLength', 'paging']
            }
        });
    } );

    function handleError(message) {
        submissionMessageDiv.style.display = 'block';
        submissionMessageDiv.innerHTML = `<ul class="messages"><li class="error">An error occurred: ${message}</li></ul>`;
    }

    function submitWatchForm() {
        const form = document.getElementById('watch-form');
        const formData = new FormData(form);
    
        fetch(form.action, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: formData,
        }).then(response => {
            if (!response.ok) {
                handleError('Failed to update the watch status.');
            }
        }).catch(error => {
            handleError(error.message);
        });
    }

    </script>
{% endblock content %}